name: "Default Workflow"

on: push

jobs:
  call-workflow-ci-java-gradle:
    uses: kumabes-org/reusable-workflows-ci-java-gradle/.github/workflows/ci.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "production"
      working-directory: "app"
      shell: "bash"
      project-name: "springboot3"
      java-distribution: "zulu"
      java-version: "17"
      gradle-version: "9.0"
    secrets: inherit

  call-workflow-sonarqube:
    needs:
      - call-workflow-ci-java-gradle
    uses: kumabes-org/reusable-workflows-sonarqube/.github/workflows/main.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "production"
      working-directory: "app"
      shell: "bash"
      project-name: "springboot3"
      language: "java"
      build: "gradle"
    secrets: inherit

  call-workflow-codeql:
    needs:
      - call-workflow-ci-java-gradle
    uses: kumabes-org/reusable-workflows-codeql/.github/workflows/main.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "production"
      working-directory: "app"
      shell: "bash"
      project-name: "springboot3"
      languages: "java"
    secrets: inherit
